name: Validate Nix Flake
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --accept-flake-config
