name: Dead code analysis
on: [push, pull_request, workflow_dispatch]
jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: astro/deadnix-action@main
        with:
          commit_message: "💚: remove dead code"
