name: Formatting Check
on: [push, pull_request, workflow_dispatch]
jobs:
  checks:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix fmt -- --fail-on-change