name: Lint Nix code
on: [push, pull_request, workflow_dispatch]
jobs:
  statix:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: jocelynthode/statix-action@master
